# Generated by Django 4.0.4 on 2022-06-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=30)),
                ('ae_title', models.CharField(max_length=30)),
                ('port_num', models.IntegerField()),
            ],
        ),
    ]
