# Generated by Django 4.0.4 on 2022-06-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfo',
            old_name='ae_title',
            new_name='AE_Title',
        ),
        migrations.RenameField(
            model_name='serverinfo',
            old_name='port_num',
            new_name='port',
        ),
    ]
