# Generated by Django 4.0.4 on 2022-06-14 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ae_title_serverinfo_ae_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(max_length=64, unique=True)),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('hostname', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='ServerInfo',
        ),
    ]
