# Generated by Django 4.0.4 on 2022-07-09 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dicomserver_delete_serverinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomserver',
            options={'verbose_name': 'DICOM Server', 'verbose_name_plural': 'DICOM Servers'},
        ),
        migrations.AlterField(
            model_name='dicomserver',
            name='ae_title',
            field=models.CharField(max_length=64, unique=True, verbose_name='AE Title'),
        ),
        migrations.AlterField(
            model_name='dicomserver',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='Hostname (friendly name)'),
        ),
        migrations.AlterField(
            model_name='dicomserver',
            name='port',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)], verbose_name='Port Number'),
        ),
    ]
