# Generated by Django 4.0.6 on 2022-07-10 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='Hostname (friendly name)')),
                ('ae_title', models.CharField(max_length=64, verbose_name='AE Title')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', help_text='IP Address of DICOM server (default is localhost 127.0.0.1)', verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)], verbose_name='Port Number')),
            ],
            options={
                'verbose_name': 'DICOM Server',
                'verbose_name_plural': 'DICOM Servers',
            },
        ),
    ]
