# Generated by Django 4.0.4 on 2022-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomserver',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
