# Generated by Django 4.0.4 on 2022-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dicomserver_output_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomserver',
            name='output_directory',
            field=models.CharField(default='djicom_output/output', help_text='The output directory where studies will be stored.', max_length=255),
        ),
    ]
